libbpf/libbpf-bootstrap

src/Makefile
Add architecture-specific headers to the BPF compilation command,
otherwise they're missing on some systems (at least on x86-64 Ubuntu).
Fixes #1
=> makefile: fix build of minimal

src/minimal.c
Update global variables from user-space after skeleton was loaded creates issue in old version of Kernel. Hence split the __open_and_load() into separate __open() and __load() to introduce initialization before __load()
=> minimal: Split open and load in minimal.c as it creates issue in old Kernel version

src/Makefile
Avoid dependency on up-to-date Linux UAPI headers (mainly linux/bpf.h and
linux/btf.h) by using headers distributed with libbpf for its own compilation
needs.
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
=> makefile: use Linux UAPI headers distributed with libbpf

README.md, src/fentry.bpf.c, src/kprobe.bpf.c
As suggested in #7, this changes the fentry and kprobe examples so that now they hook do_unlinkat() instead of bprm_execve().
I hope this will be fine as the function hasn't been changed in a while, is easy to trigger, and most of the example remains the same.
I've updated the README, and removed the part about pahole 1.19, as this function isn't static.
=> fentry, kprobe: attach fentry and kprobe examples to do_unlinkat()

examples/c/fentry.bpf.c, examples/c/kprobe.bpf.c
Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>
=> fentry, kprobe: use process ID instead of thread ID

.gitignore, README.md, examples/c/xmake.lua
Related issues: https://github.com/libbpf/libbpf-bootstrap/issues/17
I disable kprobe for android now, because it will compile fail if I use current vmlinux.h.
```console
$ xmake 
[ 20%]: compiling.bpf minimal.bpf.c
[ 20%]: compiling.bpf bootstrap.bpf.c
[ 20%]: compiling.bpf kprobe.bpf.c
[ 20%]: compiling.bpf fentry.bpf.c
error: kprobe.bpf.c:11:5: error: no member named 'uregs' in 'struct pt_regs'
int BPF_KPROBE(do_unlinkat, int dfd, struct filename *name)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ruki/.xmake/packages/l/libbpf/v0.3/3fdb468c64a048da9c2e51edfd3a7afc/include/bpf/bpf_tracing.h:385:20: note: expanded from macro 'BPF_KPROBE'
return ____##name(___bpf_kprobe_args(args));                        \
^~~~~~~~~~~~~~~~~~~~~~~~ …
```
=> add xmake.lua to build bpf c examples

examples/c/fentry.c, examples/c/kprobe.c, examples/c/minimal.c, examples/c/uprobe.c
Like in the fentry and kprobe examples, show the instructions of how to
get the trace output in the start message.
Also add a space after the command in all examples.
=> examples/c: add output trace instructions to minimal and uprobe examples

README.md
Since the example uses a build script, using the cargo plugin commands in the example is redundant.
Removing it would clarify the build process.
=> Remove Rust's redundant build commands

examples/rust/Cargo.toml, examples/rust/tracecon/.gitignore, examples/rust/tracecon/Cargo.lock, examples/rust/tracecon/Cargo.toml, examples/rust/tracecon/README.md, examples/rust/tracecon/Vagrantfile, examples/rust/tracecon/build.rs, examples/rust/tracecon/src/bpf/tracecon.bpf.c, examples/rust/tracecon/src/main.rs
Added a sample application for libbpf-rs. It will output all TCPv4 connections that have been established on the host as ips and hostnames by probing `tcp_v4_connect` in kernel and glibc's `getaddrinfo` in userland. On a successful host lookup the first result will be stored in a hashmap, which can be used as a lookup table to retrieve a hostname for ip_v4 connections. When the program is started there should be console output when TCPv4 connections are established on the system, eg. via curl:
```bash   
host event: www.jsonplaceholder.com
ip event: 172.67.201.157
```
=> Add example for uprobes and kprobes

examples/rust/tracecon/README.md
need `uname -r` for `/boot/config-$(uname -r)`, not `uname -a`
=> correct uname invocation in rust/tracecon README

examples/c/xmake.lua
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
Adds a missing target (uprobe example) to xmake.lua
=> update: add missing target for uprobe example

examples/c/Makefile
Currently `aarch64` is not present in the supported arch list `__TARGET_ARCH_xxx`: https://github.com/torvalds/linux/blob/master/tools/lib/bpf/bpf_tracing.h#L6-L29
To successfully compile the example/c programs, we need a conversion from `aarch64` to `arm64`.
---
UPDATE:
Align to the BCC makefile for more elegant conversion of differnet architectures:
https://github.com/iovisor/bcc/blob/master/libbpf-tools/Makefile#L12
=> examples/c: convertion between different architectures

examples/rust/tracecon/src/main.rs
The tracecon example tries to read the glibc library
"/lib/x86_64-linux-gnu/libc.so.6", but normally in rpm
system it is located in "/lib64/libc.so.6".
With the current implementation you got the following error:
`Error: No such file or directory (os error 2)`
PR changes:
```
Error: could not read file `/lib/x86_64-linux-gnu/libc.so.6`
Caused by:
No such file or directory (os error 2)
```
It provides some more context on which file was not able to open, then you can check the options and run it providing the correct glibc:
`cargo run -- --glibc /lib64/libc.so.6`
=> examples/rust: provide file name context

examples/c/CMakeLists.txt
Ref: #70.
Because tools/bpftool no longer exists, we need to build bpftool from git submodule and set the correct executable path in cmake variable `BPFOBJECT_BPFTOOL_EXE`.
=> examples/c: Build bpftool submodule in cmake

examples/c/Makefile
Hi team, 
This commit is to add cross-compile support,  previous related commit is https://github.com/libbpf/libbpf/pull/495
With these 2 commits, I verified cross compilation for arm64 is good.
Using target toolchain to compile code except for blktool.
=> Makefile: add support for cross compilation

README.md, examples/c/Makefile, examples/c/minimal_legacy.bpf.c, examples/c/minimal_legacy.c
As requested in #68 discussion, this PR adds a new minimal_legacy example for running on kernels that do not support global variables.
=> Add new minimal_legacy example

examples/c/profile.c, examples/rust/Cargo.lock, examples/rust/profile/src/main.rs
BlazeSym has API changes before officially releasing v0.1.0.
The major changes are renaming SymbolFileCfg to SymbolSrcCfg and renaming sym_file_cfg to sym_src_cfg.
=> Update profile for the changes of blazesym API.

.gitmodules, examples/rust/Cargo.lock, examples/rust/profile/Cargo.toml
BlazeSym moved to a new location, but still on githbu.  Although
github would redirect to the new location automatically, we still
change URLs to the new location just in case.
Signed-off-by: Kui-Feng Lee <kuifeng@fb.com>
=> Fix URLs of the repository of BlazeSym.

README.md, examples/c/Makefile, examples/c/sockfilter.bpf.c, examples/c/sockfilter.c, examples/c/sockfilter.h
This is a simplified example I port from linux `samples/bpf` directory, many code snippet came from there.
In this example, I opened a `SOCK_RAW` socket in `lo` interface, then attach it to the bpf program for monitoring.
I use `BPF_MAP_TYPE_RINGBUF` to carry information back to user space program, and the user space program will print formatted information to stdout, for example:
```
interface:lo    protocol: UDP   127.0.0.1:51845(src) -> 127.0.0.1:53(dst)
interface:lo    protocol: UDP   127.0.0.1:41552(src) -> 127.0.0.1:53(dst)
```
Currently, most of the IPv4 protocols defined in `uapi/linux/in.h` are included, please check `ipproto_mapping` for the supported protocols.
Another thing to be done is that we need to add another linux uapi header into `libbpf` submodule : …
=> examples/c: add socket filter example

tools/cmake/FindBpfObject.cmake
According to #104, cmake can not get a correct ARCH (such as arm64 for aarch64 platform) and raise an GCC error("Must specify a BPF target arch via __TARGET_ARCH_xxx") when target platform is aarch64 or some else. This PR is going to fix it.
=> tools: Fix cmake ARCH error for aarch64 etc.

examples/c/Makefile
Doing cross-compilation (issue #140) need a way to specify the target platform.  However, the makefile also detects architecture by calling `uname` on the building machine.  This patch lets users to config it by defining ARCH.  For example, 'make ARCH=arm64' will build against arm64 as the target platform.
Signed-off-by: Kui-Feng Lee <kuifeng@meta.com>
=> Make ARCH configurable.

examples/c/CMakeLists.txt
If include `<bpf/btf.h>` and compile with CMake on some machines with legacy kernels, you may hit this error:
```
src/build/libbpf/bpf/btf.h:10:10: fatal error: linux/btf.h: No such file or directory
#include <linux/btf.h>
^~~~~~~~~~~~~
compilation terminated.
```
I think it's due to `../../libbpf/include/uapi` not includes as it is at [Makefile#L18](https://github.com/libbpf/libbpf-bootstrap/blob/c58877bf5895dd5015550d4624f68a6ff0ed4b33/examples/c/Makefile#L18)
After the fix, a dir containing uapi headers will be created under the `build` dir
```
$ ls build/libbpf/linux
bpf_common.h  bpf.h  btf.h                                                                        
```
=> cmake: Fix btf header missing in legacy kernel env. 

.github/docker/Dockerfile.ubuntu, .github/workflows/build.yml
Upstream llvm moved to 17, so we need to accommodate 16 as being not the latest version. Also add another build step for validating llvm 17.
=> ci: add llvm 17 build test and fix CI for llvm 16

examples/rust/Cargo.lock, examples/rust/profile/Cargo.toml
We already pull in a snapshot of blazesym for the generation of C headers and the creation of a library.
Let's also use that in the Rust examples, instead of reaching out to `crates.io`, to use the same baseline everywhere.
=> Use local blazesym snapshot for Rust examples

examples/c/CMakeLists.txt
application build requires bpftool or it fails like this:
```
bash: line 1: libbpf-bootstrap/examples/c/build/bpftool/bootstrap/bpftool:
No such file or directory
```
add bpftool build to the dependency list of the application build to fix it.
Signed-off-by: runsisi <runsisi@hust.edu.cn>
=> cmake: fix missing dependency on bpftool build

examples/c/Makefile
Sometimes it's necessary to replace `CLANG_BPF_SYS_INCLUDES` by another value when build platform differs from host. For example, we can do something like this in Buildroot package for `libbpf-bootstrap`:
make ... CLANG_BPF_SYS_INCLUDES="$(STAGING_DIR)/usr/include"
Otherwise, clang uses host's Linux headers instead of target's.
=> examples/c: make CLANG_BPF_SYS_INCLUDES substitutable

examples/c/profile.c, examples/c/profile.h
In the current implementation, if I try to run `example/c/profile` in a virtual machine, `libbpf_num_possible_cpus` will get the wrong number of CPUs, causing the program to exit and throw an error: `Fail to set up performance monitor on a CPU/Core` because the wrong CPU id is passed to `syscall` and throwing `No such device`
The Rust version (`example/rust/profile`) of the implementation ignores this error and continues to execute `bpf_program__attach_perf_event`, which throws `invalid perf event FD -1`, but profile can still be used because `bpf_program__attach_perf_event handles` the case of passing the wrong CPU id.
This fix has only been applied to the C(`example/c/profile`).
=> Avoid profiling offline or not present CPUs

README.md, examples/c/minimal_ns.bpf.c, examples/c/minimal_ns.c
Currently minimal example does not work in environments which are inside a process namespace, like docker containers or WSL2, because the pid of the `minimal` process inside the userspace is not equal to `tgid` of that process in the bpf.
this is the fix.
=> Minimal Example fix for pid problem in process namespaces envs like containers or WSL2

README.md
Add the note about needing at least Clang v11 to successfully compile examples.
=> readme: add minimal Clang version (v11)

README.md, examples/c/sockfilter.c
When we have multiple calls to `inet_ntoa()`, this function might return the same char* even though the underlying string has been modified.
We'll get the same string if we use this function in a row in a single printf function(because char* pointed to the same location).
On the other hand, support `-i <interface>` option in sockfilter program.
=> fix: sockfilter example output

.github/docker/Dockerfile.ubuntu, .github/workflows/build.yml
LLVM/Clang 18 is available now, run against it as well. This also should fix current LLVM 17 failure, which assumes LLVM 17 is the latest one.
=> ci: add llvm-18 tests

examples/c/profile.c, examples/rust/Cargo.lock, examples/rust/Cargo.toml, examples/rust/profile/Cargo.toml, examples/rust/profile/src/main.rs
Please see individual commits for descriptions.
=> Update blazesym snapshot and profile example

examples/c/uprobe.c
The code changes in this commit is trying to improve the functionality of the `uprobe` by using the function name instead of the function offset, with bpf_program__attach_uprobe_opts.
This change is made to simplify the code and make it more readable.
It has been tested locally.
=> examples/c: improve uprobe with function name

examples/c/uprobe.bpf.c
Some archs, like arm64, use userspace pt_regs in bpf_tracing.h. When cross compiling arm64 bpf examples in x86_64 host, clang cannot find the arch specific uapi ptrace.h, which causing below compiling errror,
"
uprobe.bpf.c:11:5: error: incomplete definition of type 'struct user_pt_regs'
11 | int BPF_KPROBE(uprobe_add, int a, int b)
"
Using arch specific vmlinux.h fix this issue.
=> example/c: fix uprobe cross compiling issue

examples/c/usdt.bpf.c
Fix 'libbpf: failed to find BTF info for global/extern symbol' since uninitialized global variables on Ubuntu 20.04.6 with clang 10. 
I was able to compile on a newer ubuntu with a higher version of clang. 
However, on a development module (nVidia Orin AGX) running Ubuntu 20.04.6 LTS with clang version 10.0.0-4ubuntu1, it is not possible to use apt to update clang to a new version. Downloading the source code of a higher version of clang for compilation is cumbersome. 
So I hope that with the change, the project code can be easily compiled and used in earlier os.
=> c/usdt: fix a compiling error

tools/cmake/FindBpfObject.cmake
The original code will generate an error when compiled on the riscv64 platform:
`error: Must specify a BPF target arch via __TARGET_ARCH_xxx`
This patch fixs it.
=> tools:cmake: ARCH supports riscv64

.github/workflows/build-android.yml, examples/c/xmake.lua
https://github.com/libbpf/libbpf-bootstrap/issues/228
https://github.com/libbpf/libbpf-bootstrap/pull/234
=> Improve xmake.lua for android

.github/workflows/build-android.yml, examples/c/xmake.lua
https://github.com/libbpf/bpftool/issues/77
https://github.com/libbpf/bpftool/issues/120
https://github.com/libbpf/libbpf-bootstrap/issues
=> Fix unsupported map linkage static.

examples/c/profile.c, examples/rust/Cargo.lock, examples/rust/profile/src/main.rs
Update the `blazesym` submodule to version `0.2.0-alpha.8`.
=> deps: update blazesym submodule to v0.2.0-alpha.8

examples/c/uprobe.c
Depending on compiler, uprobe_add/uprobe_sub can still be inlined. Use no-op volatile asm and noinline attribute to prevent compiler from inlining. Just global function is not enough.
=> examples/c: prevent uprobe_add/uprobe_sub inlining

examples/rust/Cargo.lock, examples/rust/profile/Cargo.toml, examples/rust/profile/build.rs, examples/rust/profile/src/main.rs
The error handling in the profile example is insufficient. Specifically, we never check for the success of `perf_event_open`. If it fails, we end up passing an FD of -1 to libbpf's `bpf_program__attach_perf_event_opts`, which in turns barks at us.
Make sure to properly check for errors. Also address clippy issues and improper formatting along the way.
=> examples/rust: Fix improper error handling

examples/rust/profile/build.rs, examples/rust/profile/src/bpf/vmlinux.h, examples/rust/profile/src/main.rs, examples/rust/tracecon/build.rs, examples/rust/tracecon/src/bpf/vmlinux.h, examples/rust/tracecon/src/main.rs, examples/rust/xdp/build.rs, examples/rust/xdp/src/bpf/vmlinux.h, examples/rust/xdp/src/main.rs
Store skeletons in $OUT_DIR as opposed to .output, which is kind of the proper thing to do (though it certainly doesn't help discoverability...) and it is more in line with how examples in libbpf-rs work. Also remove the "there is hope!" comments, because even with https://github.com/rust-lang/rust/pull/83366 resolved we still cannot use the concat! macro in #[path = ...] attributes. All hope is lost.
=> examples/rust: Store skeletons in $OUT_DIR

README.md
Update the section about the profile example in the README, showcasing the updated format and linking to blazesym.
=> readme: Few changes to profile section

README.md, examples/c/.gitignore, examples/c/Makefile, examples/c/lsm.bpf.c, examples/c/lsm.c
It requires running on a kernel version >= 5.7 and necessitates the kernel having LSM enabled. For implementation details, please refer to the lsm.c file.
=> Add an LSM BPF sample program

.github/workflows/build-android.yml, .github/workflows/build.yml
Let's have regular daily CI build test runs.
=> ci: run build workflows daily

examples/c/CMakeLists.txt
There're some updates in Makefile in commit 4b207312dd. But it's not synchronized into CMakeLists.txt. It causes the error in below.
77%] Building C object CMakeFiles/profile.dir/profile.c.o
libbpf-bootstrap/examples/c/profile.c:17:10: fatal error: blazesym.h: No such file or directory
17 | #include "blazesym.h"
|          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/profile.dir/build.make:84: CMakeFiles/profile.dir/profile.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:520: CMakeFiles/profile.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
=> fix missing blazesym head file

examples/rust/profile/build.rs, examples/rust/tracecon/build.rs, examples/rust/xdp/build.rs
As per #257, it appears as if `std::env::consts::ARCH` does not get updated to the target architecture in a cross-compilation context. Switch to using the `CARGO_CFG_TARGET_ARCH` environment variable in the hopes that we get the desired behavior.
=> examples/rust: Use `CARGO_CFG_TARGET_ARCH` environment variable

.github/docker/Dockerfile.ubuntu, .github/workflows/build.yml, examples/c/CMakeLists.txt
As #258 showed, we also have a CMake based build infrastructure lying around for the examples. However, currently it is not used in CI and, hence, prone to breakage.
Change that fact by building using CMake as part of the build workflow.
=> examples/c: Use CMake stuff in CI

examples/rust/Cargo.lock
Run `cargo update` for the Rust examples to get the most recent version of dependencies.
=> deps: update Cargo.lock

examples/rust/Cargo.lock
Update the blazesym submodule to version 0.2.0-rc.0 (well, actually to 0.1.0-rc.0 of blazesym-c, but they are effectively the same).
=> deps: update blazesym submodule to v0.2.0-rc.0

examples/c/profile.c
Report proper errors when symbolization fails and bail out early.
=> c/profile: Short circuit on errors

examples/c/profile.c, examples/rust/Cargo.lock
Update the blazesym submodule to version 0.2.0-rc.1 (well, actually to 0.1.0-rc.1 of blazesym-c, but they are effectively the same).
=> deps: update blazesym submodule to v0.2.0-rc.1

examples/rust/Cargo.lock
Update the blazesym submodule to version 0.2.0-rc.2 (well, actually to 0.1.0-rc.2 of blazesym-c, but they are effectively the same).
=> deps: update blazesym submodule to v0.2.0-rc.2

examples/c/profile.c, examples/rust/profile/src/main.rs, examples/rust/profile/src/syscall.rs
Fix #313 
This PR introduces a new command line argument to the profile example, allowing users to specify the platform type (`host` or `guest`, default is `host`). This ensures the correct performance monitoring attributes are used based on user's input.
Key Changes:
1. Adjust performance monitoring attributes based on the `-p` argument.
2. Provide a hint when a `perf_event_open` error occurs, recommending the `-p guest` option for virtual machines.
=> Profile: command line switch for virtual machine

README.md
According to [this page of unr tutorial](https://www.unr.edu/writing-speaking-center/writing-speaking-resources/parenthetical-phrases), parenthetical phrases in the middle of sentence is good to go with commas before and after themselves.
=> Improve readability of documentation

.github/dependabot.yml
The main reason we enabled Dependabot for the repository was to keep the `libbpf-rs` version we use in-sync with current upstream releases, but by default it manages all other dependencies as well. Configure it so that it only manages `libbpf-rs`.
=> Have Dependabot only update libbpf-rs

examples/rust/profile/src/main.rs, examples/rust/profile/src/syscall.rs
Simplify the perf event open code. Less leakage, less noise, same functionality (?).
=> examples/rust: Simplify profile perf event code

examples/rust/Cargo.lock, examples/rust/profile/src/main.rs
Update the `blazesym` submodule to version `0.2.0-rc.3` (well, actually to `0.1.0` of `blazesym-c`, but they are effectively the same).
=> deps: update blazesym submodule to v0.2.0-rc.3

examples/c/profile.c
Use the inlined name instead of the
sym name.
=> Fix blazesym inlined function name

examples/rust/profile/Cargo.toml, examples/rust/tracecon/Cargo.toml, examples/rust/xdp/Cargo.toml
This reverts commit 0c8ddaae3842c6d3441484a98c6e826323ca435d.
=> Revert "examples/rust: Don't specify minimum Rust version for examples"
