src/.gitignore, src/Makefile, src/uprobe.bpf.c, src/uprobe.c
Add another example of dealing with uprobe and uretprobe.
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
=> uprobe: minimal example of doing uprobe/uretprobe BPF programs

.github/docker/Dockerfile.ubuntu, .github/workflows/build.yml
Simple CI workflow that will build both C and Rust examples.
=> [ci] introduce CI to build examples against LLVM 14 to 16

README.md, examples/c/.gitignore, examples/c/Makefile, examples/c/tc.bpf.c, examples/c/tc.c
Add a TC example to showcase the libbpf TC APIs.
Also serve as an answer to question raised in this discussion ([0]).
[0]: https://github.com/libbpf/libbpf-bootstrap/discussions/101
Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>
=> examples/c: Add TC example

examples/c/xmake.lua
https://github.com/libbpf/libbpf-bootstrap/issues/107
=> fix duplicate main error for android #107

examples/c/CMakeLists.txt, tools/cmake/FindBpfObject.cmake
1. Fix bpftool build error, follow commit fc28424eb3f0e39cfb5959296b070389b9a8bd8f to make bootstrap only and set the right path.
```
jit_disasm.c: In function ‘disasm_print_insn’:
jit_disasm.c:102:17: error: too few arguments to function ‘init_disassemble_info’
102 |                 init_disassemble_info(&info, stdout,
|                 ^~~~~~~~~~~~~~~~~~~~~
In file included from jit_disasm.c:23:
/usr/include/dis-asm.h:472:13: note: declared here
472 | extern void init_disassemble_info (struct disassemble_info *dinfo, void *stream,
|             ^~~~~~~~~~~~~~~~~~~~~
jit_disasm.c:105:17: error: too few arguments to function ‘init_disassemble_info’
105 |                 init_disassemble_info(&info, stdout,
|                 ^~~~~~~~~~~~~~~~~~~~~
/usr/include/dis-asm.h:472:13: note: …
```
=> Examples' CMake build fix

README.md
=> readme: add Github Actions status badge

examples/c/Makefile
=> Replace llvm-strip symlink with BPF static linking

examples/c/.gitignore, examples/c/Makefile, examples/c/ksyscall.bpf.c, examples/c/ksyscall.c
Adding an example for ksyscall as said in #106
=> examples/c: Add ksyscall example

.github/docker/Dockerfile.ubuntu, .github/workflows/build.yml
Add 10-13 versions, just to try it out.
=> ci: add more clang versions to test build on

examples/c/Makefile, examples/c/profile.c, examples/rust/Cargo.lock, examples/rust/profile/Cargo.toml, examples/rust/profile/src/main.rs
Update the blazesym submodule to the most recent snapshot.
=> deps: update blazesym submodule

examples/c/profile.c, examples/rust/Cargo.lock, examples/rust/profile/src/main.rs
Update the blazesym submodule to version `0.2.0-alpha.7`.
=> deps: update blazesym submodule to v0.2.0-alpha.7

README.md, examples/c/.gitignore, examples/c/Makefile, examples/c/task_iter.bpf.c, examples/c/task_iter.c, examples/c/task_iter.h
This is a simple example of using BPF iterators, which iterates over all tasks on the host.
=> examples/c: Add task_iter

.github/docker/Dockerfile.ubuntu, .github/workflows/build.yml
Update everything to fetch llvm-18/clang-18 properly, and add llvm-19 build test.
=> ci: llvm-19 is here, add it and make sure llvm-18 is found

examples/c/xmake.lua
Fix android ndk version
https://github.com/libbpf/libbpf-bootstrap/pull/245
=> limit ndk version

examples/c/Makefile, examples/c/profile.c, examples/rust/Cargo.lock, examples/rust/profile/src/main.rs
Update the blazesym submodule to version 0.2.0-alpha.11.
=> deps: update blazesym submodule to v0.2.0-alpha.11

examples/c/.gitignore, examples/c/Makefile
minimal_ns was missed, add it to .gitignore and APPS list.
=> examples/c: add minimal_ns to the list of built app

.github/docker/Dockerfile.ubuntu, .github/workflows/build.yml
It's that time of year again, we need more Clang versions.
=> ci: add Clang 20

tools/cmake/FindBpfObject.cmake
It is quite common that a `.bpf.c` file depends on a header file. 
However, the current `FindBpfObject.cmake` does not allow one to specify such dependency, so modification to the header file does not trigger recompilation of the BPF object file (and subsequent skeleton header).
This PR addresses the issue by allowing one to write, for example, 
```
bpf_object(app app.bpf.c app.h utils.h)
```
So that the change to the header files (`app.h` and `utils.h` is tracked).
=> cmake: Allow additional header deps for `bpf_object`

.github/docker/Dockerfile.ubuntu
Seems like LLVM 20 had a release.
=> ci: fix LLVM 20 build

tools/cmake/FindBpfObject.cmake
In case where BPFOBJECT_VMLINUX_H is not set and BPFOBJECT_BPFTOOL_EXE is set but not compiled yet, we need to make sure cmake compiles bpftool before attempting to generate vmlinux.h using it
=> Fix vmlinux.h creation when not specified by user
